export const TERMS = [
    <p><strong>1. Wprowadzenie </strong></p>,
    <p>Witamy na naszej stronie internetowej. Korzystając ze strony, akceptujesz niniejsze Warunki. Przeczytaj je uważnie przed
        kontynuowaniem.</p>,
    <p><strong>2. Korzystanie z Usługi</strong></p>,
    <p>Możesz używać strony wyłącznie w celu planowania wizyt u specjalisty.</p>,
    <p><strong>3. Obowiązki Użytkownika</strong></p>,
    <p>Upewnij się, że informacje podane podczas rezerwacji wizyty są poprawne.</p>,
    <p>Przychodź na umówione wizyty punktualnie lub powiadom specjalistę w przypadku opóźnień lub odwołań.</p>,
    <p>Strona nie ponosi odpowiedzialności za pominięte lub odwołane wizyty.</p>,
    <p><strong>4. Ograniczenie odpowiedzialności</strong></p>,
    <p>Strona jest udostępniana „w stanie, w jakim się znajduje”. Nie udzielamy żadnych gwarancji, wyraźnych ani
        dorozumianych, co do niezawodności lub dostępności usługi.</p>,
    <p><strong>5. Polityka prywatności</strong></p>,
    <p>Korzystając z usługi, akceptujesz naszą Politykę prywatności, która wyjaśnia, w jaki sposób zbieramy,
        wykorzystujemy i chronimy Twoje dane osobowe.</p>,
    <p><strong>6. Zmiany w Warunkach</strong></p>,
    <p>Zastrzegamy sobie prawo do aktualizacji lub modyfikacji niniejszych Warunków w dowolnym momencie.</p>,
    <p><strong>7. Informacje kontaktowe</strong></p>,
    <p>Jeśli masz jakiekolwiek pytania dotyczące niniejszych Warunków, skontaktuj się z nami.</p>,
    <br/>,
    <p><strong>Polityka prywatności</strong></p>,
    <br/>,
    <p><strong>Wprowadzenie</strong></p>,
    <p>Niniejsza Polityka prywatności opisuje, w jaki sposób zbieramy, wykorzystujemy i chronimy dane osobowe, które podajesz podczas korzystania z naszej usługi.</p>,
    <p><strong>Gromadzone przez nas dane</strong></p>,
    <p>Kiedy korzystasz ze strony, możemy zbierać następujące dane osobowe:</p>,
    <p>- Imię i nazwisko,</p>,
    <p>- Adres e-mail,</p>,
    <p>- Numer telefonu,</p>,
    <p>- Data i godzina wizyty.</p>,
    <p><strong>Jak wykorzystujemy Twoje dane</strong></p>,
    <p>Zgromadzone dane osobowe wykorzystujemy do:</p>,
    <p>- Ułatwiania umawiania wizyt u specjalisty,</p>,
    <p>- Wysyłania potwierdzeń wizyt,</p>,
    <p>- Komunikowania się z użytkownikami w sprawie ich wizyt.</p>,
    <p><strong>Udostępnianie danych</strong></p>,
    <p>Udostępniamy Twoje dane osobowe specjaliście wyłącznie w celu zarządzania wizytami. Nie sprzedajemy ani nie udostępniamy Twoich danych stronom trzecim w celach marketingowych</p>,
    <p><strong>Bezpieczeństwo danych</strong></p>,
    <p>Podejmujemy rozsądne środki w celu ochrony Twoich danych osobowych przed nieautoryzowanym dostępem, utratą lub niewłaściwym wykorzystaniem. Jednak żadna metoda przesyłania danych przez Internet nie jest w 100% bezpieczna</p>,
    <p><strong>Prawa użytkownika</strong></p>,
    <p>Masz prawo do dostępu do danych osobowych, które o Tobie posiadamy, żądania poprawienia nieprawidłowych lub niekompletnych danych, żądania usunięcia Twoich danych. Aby skorzystać z tych praw, skontaktuj się z nami.</p>,
]
