export enum ROUTES {
    HOME = '/',
    ADMIN = '/admin',
    CALENDAR = '/kalendarz',
    VISITS = '/wizyty',
    MY_VISITS = '/moje-wizyty',
    MAKE_VISIT = '/umow-wizyte',
    ABOUT_ME = '/o-mnie',
    COMMUTE = '/dojazd',
    CONTACT = '/kontakt',
    REGISTER = '/register',
    LOGIN = '/login',
    USER = '/user',
    PASSWORD_LINK = '/password/reset/link',
    PASSWORD_RESET = '/password/reset/:token',
}
