export enum AtomButtonVariants {
    STANDARD_BUTTON_VARIANT = 'STANDARD',
    TEXT = 'TEXT',
    LINK = 'LINK',
    CANCEL = 'CANCEL',
    CTA_BUTTON_VARIANT = 'CTA',
    FLOATING_BUTTON_VARIANT = 'FLOATING',
}
